### ISSUE TITLE
Latest package releases not having PRs created to be merged to the dbt hub

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [dbt-labs/hub.getdbt.com#865]
Hi dbt-labs team!

I know there have been some changes to the CI/CD process for hubcap, but have noticed that two of my teams latest releases of our packages did not have PRs opened on this repo to be merged into the dbt hub. The two releases in question are below:
- [dbt_iterable_source latest release](https://github.com/fivetran/dbt_iterable_source/releases/tag/v0.3.0) vs [dbt hub latest release](https://hub.getdbt.com/fivetran/iterable_source/latest/)
- [dbt_shopify latest release](https://github.com/fivetran/dbt_shopify/releases) vs [dbt hub latest release](https://hub.getdbt.com/fivetran/shopify/latest/)

Is there anything my team should update within hubcap or within this repo to help open the PRs on new releases to be merged in to the dbt hub?

Thanks!

**Comment by VersusFacit** [comment]
Hi there, we found the rule cause; a small bug due to a misunderstood contract between hubcap and hub. 

I fixed the bug and merged your package updates :) 

shopify
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/67295367/133332951-823e6763-bc5b-46a2-adcc-7f8c6176ea36.png">
Iterable source
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/67295367/133333459-c6da5071-7f33-4895-bf33-22d2fe97a75d.png">
